#!/usr/bin/env node

// Windows does not need this
if (process.platform === 'win32') {
  process.exit(0);
}

const fs = require('fs');
const path = require('path');

// Get the installed chromium path
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const ChromiumRevision = require('puppeteer/package.json').puppeteer.chromium_revision;
const revisionInfo = Downloader.revisionInfo(Downloader.currentPlatform(), ChromiumRevision);
const chromiumPath = revisionInfo.folderPath;

// Some sneaky little helpers to get the job done
const walkSync = (d) => {
  return fs.statSync(d).isDirectory()
    ? fs.readdirSync(d).map(f => walkSync(path.join(d, f))) : d;
}
const flatten = (arr) => {
  return arr.reduce(function (flat, toFlatten) {
    return flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten);
  }, []);
};


// Walk over each file, check its executable permission and enable
// ugo+r/ugo+rx accordingly
flatten(walkSync(chromiumPath)).forEach(function(path) {
  const stat = fs.statSync(path);

  if (!stat.isFile()) {
    return;
  }

  const isExecutable = stat.mode & 0100;

  if (isExecutable) {
    fs.chmodSync(path, 0755);
  } else {
    fs.chmodSync(path, 0644);
  }
});
