#!/bin/bash

if [ -z "${1}" ]; then
  echo 'No first input image path given.'
  exit 1
fi

if [ -z "${2}" ]; then
  echo 'No second input image path given.'
  exit 1
fi

DIFF=$(compare -metric rmse "${1}" "${2}" /dev/null 2>&1 \
  | cut -d '(' -f2 \
  | tr -d ')')

DIFF=$(perl -e "print ${DIFF} * 100")

if [ -z "${DIFF}" ]; then
  echo -1
  exit
fi

echo ${DIFF}
